# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00644631d823ba3c56e9222c34ee2f1f91a6f086c25f823b23526156864b60270367d9eaefedc1efccf88625446b078f129799c21b0cbb26bfc00d538fdb46d

test:
  secret_key_base: c62128f2433f2b5c33c2b884ad51794e35021a95ab6e447497a7ff733d5036d7053eccdc6766668765bb00e5c344ea8fee3aed6f39c0affc25994a559449c47c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
